from django.conf import settings
from django.core.mail import send_mail

from .exports import _build_data_rows

_H1 = '#1F3A52'
_H2 = '#25587D'
_H3 = '#2E75B6'
_ALT = '#D9E1F2'


def _fmt(val):
    if val is None:
        return '&mdash;'
    if isinstance(val, float):
        return f'{val:,.2f}'
    return str(val)


def _th(bg, text, rowspan=None, colspan=None):
    rs = f' rowspan="{rowspan}"' if rowspan else ''
    cs = f' colspan="{colspan}"' if colspan else ''
    style = (
        f'background:{bg};color:#fff;padding:6px 8px;text-align:center;'
        'font-size:10px;font-weight:bold;border:1px solid rgba(255,255,255,0.12);'
        'white-space:nowrap;'
    )
    return f'<th{rs}{cs} style="{style}">{text}</th>'


def build_hotel_html(hotels, display_currency, meta):
    data_rows = _build_data_rows(hotels, display_currency)

    meta_parts = [meta.get('duration', 'All Dates')]
    if meta.get('vendor_name'):
        meta_parts.append(f"Vendor: {meta['vendor_name']}")
    meta_parts.append(f"Currency: {display_currency}")
    meta_str = '&nbsp;&nbsp;|&nbsp;&nbsp;'.join(meta_parts)

    # 3-row grouped header matching the frontend ledger
    header_html = (
        '<tr>'
        + _th(_H1, '#',                  rowspan=3)
        + _th(_H1, 'VENDOR',             rowspan=3)
        + _th(_H1, 'CHECKED DATE',       colspan=2)
        + _th(_H1, 'HOTEL',              rowspan=3)
        + _th(_H1, 'RES. NO',            rowspan=3)
        + _th(_H1, 'GUEST',              rowspan=3)
        + _th(_H1, 'NTS',               rowspan=3)
        + _th(_H1, 'NO. OF ROOMS',       colspan=4)
        + _th(_H1, 'ROOM RATE / NIGHT',  colspan=4)
        + _th(_H1, 'MEAL RATE / GUEST',  colspan=3)
        + _th(_H1, 'ROOM TOTAL',         rowspan=3)
        + _th(_H1, 'MEAL TOTAL',         rowspan=3)
        + _th(_H1, 'GRAND TOTAL',        rowspan=3)
        + _th(_H1, 'TYPE',               rowspan=3)
        + _th(_H1, 'BALANCE',            rowspan=3)
        + '</tr><tr>'
        + _th(_H2, 'IN')
        + _th(_H2, 'OUT')
        + _th(_H2, 'SGL') + _th(_H2, 'DBL') + _th(_H2, 'TRL') + _th(_H2, 'QUAD')
        + _th(_H2, 'SGL') + _th(_H2, 'DBL') + _th(_H2, 'TRL') + _th(_H2, 'QUAD')
        + _th(_H2, 'BF')  + _th(_H2, 'LU')  + _th(_H2, 'DI')
        + '</tr><tr>'
        + _th(_H3, 'DATE') + _th(_H3, 'DATE')
        + _th(_H3, 'QTY')  + _th(_H3, 'QTY')  + _th(_H3, 'QTY')  + _th(_H3, 'QTY')
        + _th(_H3, '/NIGHT') * 4
        + _th(_H3, '/NIGHT') * 3
        + '</tr>'
    )

    rows_html = []
    for i, row in enumerate(data_rows):
        bg = _ALT if i % 2 == 0 else '#ffffff'
        td_s = (
            f'background:{bg};padding:5px 7px;text-align:center;'
            'font-size:10px;border:1px solid #e4e8ee;white-space:nowrap;'
        )
        cells = ''.join(f'<td style="{td_s}">{_fmt(v)}</td>' for v in row)
        rows_html.append(f'<tr>{cells}</tr>')

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="font-family:Arial,Helvetica,sans-serif;margin:0;padding:24px;background:#eef2f7;">
<div style="background:#fff;max-width:1400px;margin:0 auto;border-radius:8px;overflow:hidden;
            box-shadow:0 4px 16px rgba(0,0,0,0.10);">
  <div style="background:{_H1};padding:22px 28px;">
    <h1 style="color:#fff;margin:0;font-size:20px;letter-spacing:0.4px;">Hotel Report</h1>
    <p style="color:rgba(255,255,255,0.72);margin:6px 0 0;font-size:12px;">{meta_str}</p>
  </div>
  <div style="overflow-x:auto;padding:20px 16px;">
    <table style="border-collapse:collapse;width:100%;min-width:1100px;">
      <thead>{header_html}</thead>
      <tbody>{''.join(rows_html)}</tbody>
    </table>
  </div>
  <p style="text-align:center;font-size:10px;color:#aaa;padding:12px 0;">
    Generated by MTT &mdash; Travel Management System
  </p>
</div>
</body>
</html>"""


def send_hotel_report(to_email, hotels, display_currency, meta):
    html = build_hotel_html(hotels, display_currency, meta)
    send_mail(
        subject=f"Hotel Report – {meta.get('duration', 'All Dates')}",
        message='Please open this email in an HTML-capable client to view the report.',
        from_email=settings.DEFAULT_FROM_EMAIL,
        recipient_list=[to_email],
        html_message=html,
        fail_silently=False,
    )
