# Generated by Django 5.2.15 on 2026-07-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0002_passport_organization_alter_passport_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passport',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
