# Generated by Django 4.2.30 on 2026-06-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_name', models.CharField(max_length=200)),
                ('reservation_no', models.CharField(max_length=50, unique=True)),
                ('hotel_name', models.CharField(max_length=200)),
                ('issued_date', models.DateField(db_index=True)),
                ('check_in', models.DateField(db_index=True)),
                ('check_out', models.DateField()),
                ('nights', models.PositiveSmallIntegerField(default=0)),
                ('single_qty', models.PositiveSmallIntegerField(default=0)),
                ('single_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('double_qty', models.PositiveSmallIntegerField(default=0)),
                ('double_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('triple_qty', models.PositiveSmallIntegerField(default=0)),
                ('triple_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quad_qty', models.PositiveSmallIntegerField(default=0)),
                ('quad_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meals', models.BooleanField(default=False)),
                ('bf_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('lu_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('di_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_guests', models.PositiveSmallIntegerField(default=0)),
                ('total_room_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_meal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10)),
                ('currency', models.CharField(choices=[('PKR', 'PKR'), ('SAR', 'SAR')], default='PKR', max_length=5)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pkr_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
    ]
