# Generated by Django 5.2.15 on 2026-07-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotelproperty_hotel_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
