# Generated by Django 5.2.15 on 2026-07-15 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0002_alter_vendor_email_alter_vendor_short_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('issued_date', models.DateField(db_index=True)),
                ('visa_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10)),
                ('currency', models.CharField(choices=[('PKR', 'PKR'), ('SAR', 'SAR')], default='PKR', max_length=5)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pkr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visas', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visas', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
    ]
