# Generated by Django 5.2.15 on 2026-07-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0002_visa_organization_alter_visa_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visa',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
