# Generated by Django 4.2.30 on 2026-06-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('issued_date', models.DateField(db_index=True)),
                ('departure_date', models.DateField()),
                ('adt_qty', models.PositiveSmallIntegerField(default=0)),
                ('adt_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('chd_qty', models.PositiveSmallIntegerField(default=0)),
                ('chd_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inf_qty', models.PositiveSmallIntegerField(default=0)),
                ('inf_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('no_of_tickets', models.PositiveSmallIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('payment_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10)),
                ('currency', models.CharField(choices=[('PKR', 'PKR'), ('SAR', 'SAR')], default='PKR', max_length=5)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pkr_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
    ]
