# Generated by Django 4.2.30 on 2026-06-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pkr_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
