# Generated by Django 5.2.15 on 2026-07-16 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tickets', '0003_alter_ticket_exchange_rate_alter_ticket_pkr_amount'),
        ('vendors', '0003_vendor_organization_alter_vendor_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='invoice_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('organization', 'invoice_no'), name='uniq_ticket_invoice_per_org'),
        ),
    ]
