# Generated by Django 5.2.15 on 2026-07-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='short_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
