from django.conf import settings
from django.core.mail import send_mail

from .exports import _build_rows

_H = '#1F4E79'
_ALT = '#D9E1F2'


def _fmt(val):
    if val is None:
        return '&mdash;'
    if isinstance(val, float):
        return f'{val:,.2f}'
    return str(val)


def build_visa_html(visas, display_currency, meta, options):
    headers, data_rows = _build_rows(
        visas, display_currency,
        options.get('show_vendor', False),
        options.get('show_visa_number', False),
        options.get('show_description', False),
    )

    meta_parts = [meta.get('duration', 'All Dates')]
    if meta.get('vendor_name'):
        meta_parts.append(f"Vendor: {meta['vendor_name']}")
    meta_parts.append(f"Currency: {display_currency}")
    meta_str = '&nbsp;&nbsp;|&nbsp;&nbsp;'.join(meta_parts)

    th_s = (
        f'background:{_H};color:#fff;padding:8px 10px;text-align:center;'
        'font-size:12px;font-weight:bold;border:1px solid rgba(255,255,255,0.15);'
        'white-space:nowrap;'
    )
    header_cells = ''.join(f'<th style="{th_s}">{h}</th>' for h in headers)

    rows_html = []
    for i, row in enumerate(data_rows):
        bg = _ALT if i % 2 == 0 else '#ffffff'
        td_s = (
            f'background:{bg};padding:7px 10px;text-align:center;'
            'font-size:11px;border:1px solid #e8ecf0;'
        )
        cells = ''.join(f'<td style="{td_s}">{_fmt(v)}</td>' for v in row)
        rows_html.append(f'<tr>{cells}</tr>')

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="font-family:Arial,Helvetica,sans-serif;margin:0;padding:24px;background:#eef2f7;">
<div style="background:#fff;max-width:960px;margin:0 auto;border-radius:8px;overflow:hidden;
            box-shadow:0 4px 16px rgba(0,0,0,0.10);">
  <div style="background:{_H};padding:22px 28px;">
    <h1 style="color:#fff;margin:0;font-size:20px;letter-spacing:0.4px;">Visa Report</h1>
    <p style="color:rgba(255,255,255,0.72);margin:6px 0 0;font-size:12px;">{meta_str}</p>
  </div>
  <div style="overflow-x:auto;padding:20px 16px;">
    <table style="border-collapse:collapse;width:100%;min-width:560px;">
      <thead><tr>{header_cells}</tr></thead>
      <tbody>{''.join(rows_html)}</tbody>
    </table>
  </div>
  <p style="text-align:center;font-size:10px;color:#aaa;padding:12px 0;">
    Generated by MTT &mdash; Travel Management System
  </p>
</div>
</body>
</html>"""


def send_visa_report(to_email, visas, display_currency, meta, options):
    html = build_visa_html(visas, display_currency, meta, options)
    send_mail(
        subject=f"Visa Report – {meta.get('duration', 'All Dates')}",
        message='Please open this email in an HTML-capable client to view the report.',
        from_email=settings.DEFAULT_FROM_EMAIL,
        recipient_list=[to_email],
        html_message=html,
        fail_silently=False,
    )
